name:                visualikey
version:             0.1.0.0
github:              "Patsonical/VisualiKey"
license:             GPL-2
author:              "Patsonical"
maintainer:          "patryk.kaczmarczyk.mail@gmail.com"
copyright:           "2021 Patryk Kaczmarczyk"

extra-source-files:
- README.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description: A simple command-line program to find the key of a song (queried via Tunebat.com) and display it as ASCII art 

dependencies:
- base >= 4.7 && < 5
- aeson
- bytestring
- base64-bytestring
- directory
- http-client
- http-client-tls
- http-types
- mtl
- rainbow
- req
- scalpel
- text
- time

library:
  source-dirs: src

executables:
  visualikey:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - visualikey

tests:
  visualikey-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - visualikey
